//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertiser.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advertiser.resources.DBRes", typeof(DBRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos You Like.
        /// </summary>
        internal static string applicationTitle {
            get {
                return ResourceManager.GetString("applicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/CompanyProducts.xaml.
        /// </summary>
        internal static string companyProductsListPage {
            get {
                return ResourceManager.GetString("companyProductsListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;Database name=&quot;Advertisements&quot; &gt;
        ///  &lt;Table name=&quot;product&quot; &gt;
        ///    &lt;row id=&quot;0&quot; &gt;
        ///      &lt;productname value=&quot;Mazda&quot; /&gt;
        ///      &lt;category value=&quot;automobile&quot;/&gt;
        ///      &lt;description value=&quot;Mazda&quot;/&gt;
        ///      &lt;videolink value=&quot;/resources/videos/2013Mazda.wmv&quot;/&gt;
        ///      &lt;companyid value=&quot;3&quot;/&gt;
        ///      &lt;image value=&quot;&quot;/&gt;
        ///    &lt;/row&gt;
        ///    &lt;row id=&quot;1&quot; &gt;
        ///      &lt;productname value=&quot;Galaxy_Tab&quot; /&gt;
        ///      &lt;category value=&quot;electronics&quot;/&gt;
        ///      &lt;description value=&quot;Galaxy Tab&quot;/&gt;
        ///      &lt;vi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/ProductSearch.xaml.
        /// </summary>
        internal static string productNameSearchPage {
            get {
                return ResourceManager.GetString("productNameSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/ProductSearchResults.xaml.
        /// </summary>
        internal static string productSearchResultsPage {
            get {
                return ResourceManager.GetString("productSearchResultsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/ProductVideo.xaml.
        /// </summary>
        internal static string productVideoPage {
            get {
                return ResourceManager.GetString("productVideoPage", resourceCulture);
            }
        }
    }
}
